spring:
  datasource:
    url: jdbc:mysql://mysql-nvs-project/nvs_project
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    hibernate:
      ddl-auto: none
  security:
    user:
      name: admin
      password: admin

server:
  port: 8085